### 입찰 등록
POST http://localhost:8083/api/bids
Content-Type: application/json

{
  "auctionId": 2,
  "participantMemberUsername": "seongjin2222",
  "coinId": 1,
  "coinAmount": 3.02
}

### 입찰 목록 조회
GET http://localhost:8083/api/bids

### 입찰 단건 조회
GET http://localhost:8083/api/bids/1