### 입찰 등록
POST http://localhost:8083/api/bids
Content-Type: application/json

{
  "auctionId": 1,
  "participantMemberUsername": "user1234",
  "coinId": 1,
  "coinAmount": 30.01
}

### 입찰 목록 조회
GET http://localhost:8083/api/bids

### 입찰 단건 조회
GET http://localhost:8083/api/bids/1