### bid register
POST http://localhost:8083/api/bids
Content-Type: application/json

{
  "auctionId": 1,
  "participantMemberUsername": "biggu",
  "coinId": 1,
  "coinAmount": 200.003
}

###
GET http://localhost:8083/api/bids

###
GET http://localhost:8083/api/bids/1