version: '3.8'

services:
  prometheus:  # Prometheus
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일
    networks:
      - auction-network

  grafana:  # Grafana
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - auction-network

  zipkin:  # Zipkin
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - auction-network

networks:
  auction-network: