### coin create / MASTER / init
POST http://localhost:8084/api/coins/create
Content-Type: application/json

{
  "coin_real_name": "KRW-WAVES",
  "coin_name": "wave"
}

### 코인 구매 / user : panjun
POST http://localhost:8084/api/coin_wallets
Content-Type: application/json
X-User-Name: hyeokjin

{
  "charge_amount": 200000,
  "coin_id": 3
}
