### register
POST http://localhost:8082/api/auctions
Content-Type: application/json

{
  "title": "galaxy s24",
  "image": "http://example.com/image.jpg",
  "description": "액정 고장남",
  "hopePrice": 1000,
  "coinId": 3,
  "registerMemberId": 123
}

### retrieve auction page
GET http://localhost:8082/api/auctions

### retrieve auction
GET http://localhost:8082/api/auctions/1

### get auction
GET http://localhost:8082/api/internal/auctions/1