spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/coinauction  # 여기에 실제 데이터베이스 이름을 넣으세요
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 (운영 환경에 맞게 설정)
    show-sql: true     # SQL 쿼리 로그 확인
    database-platform: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: false

  sql:
    init:
      mode: never
      data-locations: >
        classpath:data/coinpay.sql

# Hibernate 기본 설정
hibernate:
  naming:
    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

# 서버 기본 설정 (필요한 경우)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/